version: '3.4'

services:
  samba:
    image: devosku/samba
    environment:
      TZ: 'Europe/Helsinki'
    ports:
      - "139:139"
      - "445:445"
    restart: unless-stopped
    volumes:
      - ./shared:/share/folder
    command: '-u "1000:1000:oskari:oskari:put-any-password-here" -s "SmbShare:/share/folder:rw:oskari"'